### ISSUE TITLE
ENH: method name `identification` can be confusing

### ISSUE THREAD

**Issue by jankoslavic** [ladisk/pyEMA#1]
Can we come up with something better?
https://github.com/ladisk/pyEMA/blob/de3617dd20bc0b7f34b74a9f3568c8db7e25730d/pyEMA.py#L330

**Comment by klemengit** [comment]
Options: select_poles, find_closest, **select_closest_poles**

**Comment by klemengit** [comment]
Method name changed to: `select_closest_poles`. Changes were made to showcase notebook.
