### ISSUE TITLE
Small correction

### ISSUE THREAD

**Issue by ozatozat** [ladisk/pyEMA#10]
It takes some time to figure out that deleting the last pole from the graph, requires a holding shift as well. I do appreciate your work but others may have difficulties to notice this small detail.

**Comment by jankoslavic** [comment]
I agree on this; @klemengit should we add help text to the figure?

**Comment by klemengit** [comment]
I agree, the Shift information is missing, it's a small change in the code. 
In the next release, a new function for picking poles will be presented where basic help will be accessible in the help menu.

**Comment by klemengit** [comment]
The help text is now updated. The new code is available on master branch and will be in the next release.
