### ISSUE TITLE
ENH: select_poles without shift

### ISSUE THREAD

**Issue by jankoslavic** [ladisk/pyEMA#13]
Would it be possible to select poles without the shift? This would be more intuitive. (Does it interfere with the mpl interface?)

**Comment by klemengit** [comment]
The shift is not necessary, however, it is convenient for users with the mouse pad. This allows the usage of selecting the pole, deselecting the pole and still gives the option to magnify the plot and move around the plot.

**Comment by klemengit** [comment]
Added a message on the plot (in `self.select_poles()`) to improve the user experience (commit 9c088dc31a163325c444be6498ffbc54a9a5f311).
The message disappears when the first pole is selected, this ensures that the user has a clear view of all the poles.
