### ISSUE TITLE
Problem with pole_picking.py

### ISSUE THREAD

**Issue by MonashSmartStructures** [ladisk/pyEMA#15]
There is an issue with pole_picking.py

As soon as the command 
[ acc.select_poles()] is ran, the error flag appears:
Nonetype Object has no attribute draw(). 

The same error flag has been shown regardless of what IDE I used (i.e. I've tried both Jupyter Notebook and Pycharm)

**Comment by jankoslavic** [comment]
Thank you @MonashSmartStructures ! Can you please try to upgrade the matplotlib library?

**Comment by MonashSmartStructures** [comment]
Thank you! Upgrading Matplotlib to current version worked (3.3.1) . My previous version was 3.0.2

**Comment by jankoslavic** [comment]
Dear @MonashSmartStructures, this is great! Thank you for the feedback!

**Comment by jankoslavic** [comment]
PS: @klemengit we have to update the requirements!

**Comment by jankoslavic** [comment]
Done and waiting for the next release:
https://github.com/ladisk/pyEMA/commit/57eea3865c14d5862d3f02330fab0428e058d926
