### ISSUE TITLE
ENH: MAC function should also accept a single mode shape

### ISSUE THREAD

**Issue by klemengit** [ladisk/pyEMA#17]
Currently, the `MAC` function accepts only a 2D array (of shape `n_dof, n_modes`) of mode shape functions and returns a MAC matrix.
The function should be written more generally and accept two 1D mode shape arrays (of shape `n_dof`) and return a single MAC value:
```
mac = pyEMA.tools.MAC(phi_a, phi_b)
```
where
```
>>> phi_a.shape, phi_b.shape
(n_dof, ), (n_dof, )
```

Different number of modes in the matrices should also be supproted:
```
mac = pyEMA.tools.MAC(phi_a, phi_b)
```
where
```
>>> phi_a.shape, phi_b.shape
(n_dof, n_modes_1), (n_dof, n_modes_2)
```
where `n_modes_1 != n_modes_2`.

**Comment by jankoslavic** [comment]
This would be great to develop! Thanks @klemengit

**Comment by klemengit** [comment]
`tools.MAC()` function is now ugraded with commit c25f6f1f05e5e74cf392d400357d242765c4c716.
