### ISSUE TITLE
BUG: SVD does not converge 

### ISSUE THREAD

**Issue by jankoslavic** [ladisk/pyEMA#21]
If numpy is installed via pip (and not via anaconda) the SVD algorithm does not converge:
     92 
     93 def _raise_linalgerror_eigenvalues_nonconvergence(err, flag):
---> 94     raise LinAlgError("Eigenvalues did not converge")
     95 
     96 def _raise_linalgerror_svd_nonconvergence(err, flag):

We should pinpoint the problem and find a solution.

**Comment by klemengit** [comment]
I was not able to reproduce the problem on another machine yet.

To describe the problem further: the exception is returned only on the first run of the jupyter notebook cell. When running the cell the second time (with exactly the same code), the code runs OK and the results are returned.

Others have also encountered this problem. For reference:
https://stackoverflow.com/questions/63761366/numpy-linalg-linalgerror-svd-did-not-converge-in-linear-least-squares-on-first

https://stackoverflow.com/questions/63373640/svd-does-not-converge-error-when-creating-matplotlib-subplots-and-calling-np-r

**Comment by jankoslavic** [comment]
Ok. Thanks; I will close this issue for now.
