### ISSUE TITLE
ENH: pole picking should be mouse pad friendly

### ISSUE THREAD

**Issue by jankoslavic** [ladisk/pyEMA#3]
Currently, a middle-button mouse is required.

**Comment by klemengit** [comment]
Current implementation:
* Right button for pole selection
* Middle button for pole deletion (in reverse order)

The left button cannot be used, since it is needed to use navigation options in matplotlib plot.

**Comment by jankoslavic** [comment]
What about using key "shift" for deselection with right button?

**Comment by klemengit** [comment]
* For pole **selection** a **shift key + left mouse button** is used
* For pole **deselection** a **shift key + right mouse button** is used
