### ISSUE TITLE
Working example for normal mode extraction from frequency response curves

### ISSUE THREAD

**Issue by nilswagner** [ladisk/pyEMA#5]
Assume that we have a set of measured frequency response curves (i.e. Dataset 58). How can we extract normal modes and natural frequencies using pyFRF and pyEMA?
A simple self-explanatory example would be very helpful.

**Comment by nilswagner** [comment]
Dear Janko,

I am newbie to jupyter notebooks. BTW, the link to the showcase is broken
https://pypi.org/project/pyEMA/

We could use tree_structure_mini.uff from your uff_widget project as a starting point. 

import os
import sys
import numpy as np
import matplotlib.pyplot as plt
import pyEMA
import pyuff

uff_file = pyuff.UFF('tree_structure_mini.unv')
data_sets=uff_file.get_set_types()
print (data_sets)
data = uff_file.read_sets() # Load all datasets from the uff file
plt.semilogy(data[7]['x'], np.abs(data[7]['data']))
plt.xlabel('Frequency  [Hz]')
plt.ylabel('FRF Magnitude [dB m/N]')
#
# I am not sure how to continue ...FRF = ??? freq = ??? lower=?? upper = ??
#
#acc = pyEMA.lscf(frf=FRF,freq=freq,lower=10,upper=5000,pol_order_high=60)
#acc.get_poles(show_progress=True)
#acc.stab_chart(acc.all_poles, legend = True)
# Alternatively the frequencies can be defines as a list
#n_freq =  [176,476,932,1534,2258,3161,4180]
#acc.select_closest_poles(n_freq)
#frf_rec, modal_const = acc.lsfd(whose_poles='own', FRF_ind='all')
#acc.print_modal_data()
#plt.show()

**Comment by jankoslavic** [comment]
The showcase is here:
https://github.com/ladisk/pyEMA/blob/master/LSCF_Showcase.ipynb
@klemengit why did we change the name of the showcase? I will open an issue

**Comment by jankoslavic** [comment]
Dear @nilswagner 
PS: see also the readme.md
https://github.com/ladisk/pyEMA/blob/master/README.md

**Comment by nilswagner** [comment]
Dear Janko,
Your support is greatly appreciated.
How do I extract the entire frf_matrix from the universal file?

**Comment by jankoslavic** [comment]
DEar Nils, this is not an issue pyEMA is addressing. Please look at the showcase example in uff_widget.

I invite you to prepare a use case as you use it and maybe we can post is somewhere and it will help others...

**Comment by nilswagner** [comment]
I cannot install uff_widget due to
pyINTES setup.py develop --install-dir $HOME/local
running develop
running egg_info
writing uff_widget.egg-info/PKG-INFO
writing dependency_links to uff_widget.egg-info/dependency_links.txt
writing top-level names to uff_widget.egg-info/top_level.txt
reading manifest file 'uff_widget.egg-info/SOURCES.txt'
writing manifest file 'uff_widget.egg-info/SOURCES.txt'
running build_ext
Creating /home/wagner/local/uff-widget.egg-link (link to .)
uff-widget 0.1 is already the active version in easy-install.pth
error: [Errno 2] No such file or directory: '/home/wagner/git/uff_widget/uff_widget'

**Comment by jankoslavic** [comment]
I am not sure it is related, but there was a bug in the setup file. Please upgrade to the uff_widget version 0.2 and try again.

**Comment by nilswagner** [comment]
Works fine for me now! Thank you.
There are just a few warnings in pvectorcmodule.c

Running pyrsistent-0.15.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-cqr9o7mz/pyrsistent-0.15.4/egg-dist-tmp-c147h0ck
pvectorcmodule.c: In function ‘nodeFor’:
pvectorcmodule.c:152:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if((i >= 0) && (i < self->count)) {
                     ^
pvectorcmodule.c:153:10: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if(i >= TAIL_OFF(self)) {
          ^
pvectorcmodule.c: In function ‘PVector_repeat’:
pvectorcmodule.c:428:17: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
       for(j=0; j<self->count; j++) {
                 ^
pvectorcmodule.c: In function ‘extendWithItem’:
pvectorcmodule.c:145:52: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define ROOT_NODE_FULL(vec) ((vec->count >> SHIFT) > (1 << vec->shift))
                                                    ^
pvectorcmodule.c:769:8: note: in expansion of macro ‘ROOT_NODE_FULL’
     if(ROOT_NODE_FULL(newVec)) {
        ^
pvectorcmodule.c: In function ‘PVector_append’:
pvectorcmodule.c:145:52: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
 #define ROOT_NODE_FULL(vec) ((vec->count >> SHIFT) > (1 << vec->shift))
                                                    ^
pvectorcmodule.c:919:6: note: in expansion of macro ‘ROOT_NODE_FULL’
   if(ROOT_NODE_FULL(self)) {

**Comment by nilswagner** [comment]
Once the natural frequencies and modeshapes are extracted, a universal file consisting of corresponding datasets 55 should be created.

**Comment by jankoslavic** [comment]
Dear Nils, I invite you to prepare an example which will help others...

**Comment by nilswagner** [comment]
Dear Janko,
I had a short look at your showcase. What do you mean by "Modal constants"?
What is exactly the lower and upper residual?

**Comment by nilswagner** [comment]
As an introduction I created prepare_test_55 for the pyuff project. See https://github.com/openmodal/pyuff/pull/25

**Comment by jankoslavic** [comment]
Modal constants, lower and upper residuals? In short: those parameters define the modal model, one could also say the frequency response function(s)... But actually a longer answer is required and I would ask you to check a book on experimental modal analysis to get the complete story. See e.g.: https://www.amazon.de/MODAL-TESTING-Application-MECHANICAL-ENGINEERING/dp/0863802184/ref=pd_sim_14_1/258-2578407-6182226?_encoding=UTF8&pd_rd_i=0863802184&pd_rd_r=54a81120-d853-4682-ac47-a6293c4be910&pd_rd_w=ZGDpX&pd_rd_wg=NOAmK&pf_rd_p=0368299c-e45b-4d3d-bfec-931874242ef1&pf_rd_r=DF84HTX8WNY9017M268E&psc=1&refRID=DF84HTX8WNY9017M268E or https://www.bookdepository.com/Theoretical-Experimental-Modal-Analysis-Nuno-M-M-Maia/9780863802089

**Comment by jankoslavic** [comment]
I guess this issue can be closed. @nilswagner ? The showcase ipynb (please see the first page of this github repo) now also includes normal modes...
