### ISSUE TITLE
DOC: showcase name changed

### ISSUE THREAD

**Issue by jankoslavic** [ladisk/pyEMA#6]
The setup.py
https://github.com/ladisk/pyEMA/blob/master/setup.py

refers to a non-existing showcase:
https://github.com/ladisk/pyEMA/blob/master/pyEMA%20Showcase.ipynb

why did we change it to:
https://github.com/ladisk/pyEMA/blob/master/LSCF_Showcase.ipynb
?

This should be synchronized

**Comment by klemengit** [comment]
Showcase name was changed. 
https://github.com/ladisk/pyEMA/blob/master/pyEMA%20Showcase.ipynb is now valid link.
